export {
  QuizIcon,
  PlayIcon,
  StarIcon,
  CommentIcon,
  ShareIcon,
  AccuracyIcon,
  TrendingUpIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  ArrowRightIcon,
  SendIcon,
  AnnouncementIcon,
  ReleaseNoteIcon,
  CheckIcon,
  PlusIcon,
  TrashIcon,
  AlertIcon,
  PinIcon,
} from './Icon';
export type { IconProps, IconName } from './Icon.type';
